### ISSUE TITLE
Getting issue while login client

### ISSUE THREAD

**Issue by galaxyitcenter** [dietzi/yowsup#1]
DEBUG:yowsup.env.env:Current env changed to android 
Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/stacks/yowstack.py", line 10, in <module>
    from yowsup.layers.protocol_media              import YowMediaProtocolLayer
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
    from .layer import YowMediaProtocolLayer 
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/layers/protocol_media/layer.py", line 2, in <module>
    from .protocolentities import ImageDownloadableMediaMessageProtocolEntity
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/layers/protocol_media/protocolentities/__init__.py", line 3, in <module>
    from .message_media_downloadable_image import ImageDownloadableMediaMessageProtocolEntity
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 4, in <module>
    from yowsup.layers.protocol_messages.proto.wa_pb2 import ImageMessage
  File "/home/ubuntu/Documents/whatsapp/yowsup/yowsup/layers/protocol_messages/proto/wa_pb2.py", line 570, in <module>
    __module__ = 'wa_pb2'
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.4.0-py2.7.egg/google/protobuf/internal/python_message.py", line 162, in __init__
    _AttachFieldHelpers(cls, field)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.4.0-py2.7.egg/google/protobuf/internal/python_message.py", line 288, in _AttachFieldHelpers
    is_map_entry = _IsMapField(field_descriptor)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.4.0-py2.7.egg/google/protobuf/internal/python_message.py", line 265, in _IsMapField
    field.message_type.has_options and
AttributeError: 'NoneType' object has no attribute 'has_options'

**Comment by galaxyitcenter** [comment]
Solved this issue by installing pillow.. :)

**Comment by carlos-angulo** [comment]
I have the same problem and I have installed pillow

**Comment by acircuit** [comment]
Any solution to this? I am facing the same problem after installing pillow also.
